import json
import csv

def export_to_csv_and_generate_report():
    """Export results to CSV and generate comprehensive evidence report."""
    
    # Load data
    with open('data/analysis_results.json', 'r') as f:
        results = json.load(f)
    
    with open('data/analysis_stats.json', 'r') as f:
        stats = json.load(f)
    
    # Export to CSV
    with open('data/analysis_results.csv', 'w', newline='') as csvfile:
        fieldnames = ['pr_url', 'success', 'vulnerabilities', 'risk_score', 'recommendations', 'summary', 'error']
        writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
        writer.writeheader()
        
        for result in results:
            row = {
                'pr_url': result['pr_url'],
                'success': result.get('success', False),
                'error': result.get('error', '')
            }
            
            if result.get('success'):
                report = result['report']
                row.update({
                    'vulnerabilities': ';'.join(report.get('vulnerabilities', [])),
                    'risk_score': report.get('risk_score', 0),
                    'recommendations': ';'.join(report.get('recommendations', [])),
                    'summary': report.get('summary', '')
                })
            
            writer.writerow(row)
    
    # Generate evidence report
    successful_analyses = [r for r in results if r.get('success', False)]
    
    # Find smoking gun examples (high-risk PRs with multiple vulnerabilities)
    smoking_guns = []
    for result in successful_analyses:
        report = result['report']
        vulns = report.get('vulnerabilities', [])
        risk_score = report.get('risk_score', 0)
        if len(vulns) >= 2 and risk_score > 0.6:
            smoking_guns.append({
                'pr_url': result['pr_url'],
                'vulnerabilities': vulns,
                'risk_score': risk_score,
                'recommendations': report.get('recommendations', [])
            })
    
    # Create comprehensive evidence report
    report_content = f"""# FastAPI Security Agent - Evidence Report

## Executive Summary
This report presents quantitative evidence of the FastAPI Security Agent's effectiveness in detecting security vulnerabilities in GitHub Pull Requests.

## Analysis Overview
- **Total PRs Analyzed**: {stats['total_prs_analyzed']}
- **Successful Analyses**: {stats['successful_analyses']} ({stats['success_rate']}%)
- **Total Vulnerabilities Found**: {stats['total_vulnerabilities_found']}
- **Unique Vulnerability Types**: {stats['unique_vulnerability_types']}
- **Average Risk Score**: {stats['average_risk_score']}

## Key Findings

### Most Common Vulnerabilities
"""

    for vuln, count in stats['most_common_vulnerabilities']:
        report_content += f"- **{vuln}**: {count} occurrences\n"
    
    report_content += f"""

### Risk Score Distribution
- **Low Risk** (< 0.3): {stats['risk_score_distribution']['low']} PRs
- **Medium Risk** (0.3-0.7): {stats['risk_score_distribution']['medium']} PRs
- **High Risk** (> 0.7): {stats['risk_score_distribution']['high']} PRs

## Smoking Gun Examples
High-risk PRs with multiple vulnerabilities that demonstrate the tool's effectiveness:

"""
    
    for i, sg in enumerate(smoking_guns[:5], 1):  # Top 5 examples
        report_content += f"""### Example {i}: {sg['pr_url']}
- **Risk Score**: {sg['risk_score']}
- **Vulnerabilities Found**: {', '.join(sg['vulnerabilities'])}
- **Recommendations**: {'; '.join(sg['recommendations'])}
"""
    
    report_content += f"""

## Methodology
The analysis was performed using a hybrid approach combining:
1. **Static Code Analysis**: AST-based pattern detection for common vulnerabilities
2. **AI-Powered Analysis**: Gradient AI for contextual vulnerability assessment
3. **Knowledge Base Integration**: RAG system with FastAPI security documentation
4. **Multi-Agent Routing**: Specialized agents for different vulnerability types

## Impact Assessment
- **Detection Rate**: {stats['total_vulnerabilities_found']} vulnerabilities identified across {stats['successful_analyses']} PRs
- **Prevention Potential**: Early detection could prevent security issues in production
- **Developer Productivity**: Automated scanning reduces manual security review time

## Recommendations for Implementation
1. Integrate into CI/CD pipelines for automated PR scanning
2. Use as a developer tool for real-time security feedback
3. Extend analysis to other Python frameworks beyond FastAPI
4. Add support for additional vulnerability types and frameworks

## Data Export
Complete analysis results have been exported to  for further analysis and transparency.

---
*Report generated by FastAPI Security Agent - Phase 5 Data Analysis*
"""
    
    with open('data/evidence_report.md', 'w') as f:
        f.write(report_content)
    
    print(f'Exported {len(results)} results to CSV')
    print(f'Generated evidence report with {len(smoking_guns)} smoking gun examples')
    
    return {
        'csv_file': 'data/analysis_results.csv',
        'report_file': 'data/evidence_report.md',
        'smoking_guns': len(smoking_guns)
    }

if __name__ == '__main__':
    export_to_csv_and_generate_report()
